## IT IS A MACHINE LEARNING MODEL FOR SONG RECOMENDATIONS:
- data is taken from kaggle
- preprocessing is done by pandas,numpy and sklearn
- method is : we taken a count vectorizer and the nearest song is recommended

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("C:/Users/Server/Desktop/fully completed/SRS/songs_normalize.csv")

In [3]:
print(df.head())



           artist                    song  duration_ms  explicit  year  \
0  Britney Spears  Oops!...I Did It Again       211160     False  2000   
1       blink-182    All The Small Things       167066     False  1999   
2      Faith Hill                 Breathe       250546     False  1999   
3        Bon Jovi            It's My Life       224493     False  2000   
4          *NSYNC             Bye Bye Bye       200560     False  2000   

   popularity  danceability  energy  key  loudness  mode  speechiness  \
0          77         0.751   0.834    1    -5.444     0       0.0437   
1          79         0.434   0.897    0    -4.918     1       0.0488   
2          66         0.529   0.496    7    -9.007     1       0.0290   
3          78         0.551   0.913    0    -4.063     0       0.0466   
4          65         0.614   0.928    8    -4.806     0       0.0516   

   acousticness  instrumentalness  liveness  valence    tempo         genre  
0        0.3000          0.000018    0

In [4]:
df = df[['artist','song','year','genre']]

print(df.head())
print(df.shape)

           artist                    song  year         genre
0  Britney Spears  Oops!...I Did It Again  2000           pop
1       blink-182    All The Small Things  1999     rock, pop
2      Faith Hill                 Breathe  1999  pop, country
3        Bon Jovi            It's My Life  2000   rock, metal
4          *NSYNC             Bye Bye Bye  2000           pop
(2000, 4)


In [5]:
df=df.drop_duplicates()
print(df.shape)

(1930, 4)


In [6]:
df_new = df
df = df.to_numpy()


In [7]:
df_new.song

0                       Oops!...I Did It Again
1                         All The Small Things
2                                      Breathe
3                                 It's My Life
4                                  Bye Bye Bye
                         ...                  
1995                                    Sucker
1996                              Cruel Summer
1997                                The Git Up
1998    Dancing With A Stranger (with Normani)
1999                                   Circles
Name: song, Length: 1930, dtype: object

In [8]:
print(df)
print(df.ndim)

[['Britney Spears' 'Oops!...I Did It Again' 2000 'pop']
 ['blink-182' 'All The Small Things' 1999 'rock, pop']
 ['Faith Hill' 'Breathe' 1999 'pop, country']
 ...
 ['Blanco Brown' 'The Git Up' 2019 'hip hop, country']
 ['Sam Smith' 'Dancing With A Stranger (with Normani)' 2019 'pop']
 ['Post Malone' 'Circles' 2019 'hip hop']]
2


- row = np.array([1, 2]).reshape(2, 1)
- arr_row = np.append(arr, row, axis=1)


In [9]:
tags=[]
for i in df:
      valu = i[0]+" "+i[3]
      tags = np.append( tags,values=valu)
print(tags)


['Britney Spears pop' 'blink-182 rock, pop' 'Faith Hill pop, country' ...
 'Blanco Brown hip hop, country' 'Sam Smith pop' 'Post Malone hip hop']


In [10]:
print (tags.dtype)

<U58


In [11]:
tags = tags.reshape(1930,1)
print(df.shape)
print(tags.shape)
print(df.ndim)
print(tags.ndim)


(1930, 4)
(1930, 1)
2
2


In [12]:
df = np.append(df,tags,axis=1)

In [13]:
# print(df.reshape(2000,5))
print (df[0],df[34])

['Britney Spears' 'Oops!...I Did It Again' 2000 'pop' 'Britney Spears pop'] ['Britney Spears' 'Born to Make You Happy' 1999 'pop' 'Britney Spears pop']


In [14]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1000, stop_words='english')

vectors = cv.fit_transform(df[:,4]).toarray()
# vectors.get_feature_names_out()
# print( vectors.vocabulary_)
print (vectors)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [15]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [16]:
recomendation = sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:11]

In [17]:

def recommend (title):
      song_index= df_new[df_new['song'] == title].index[0]
      difference = similarity[song_index]
      song_list = sorted(list(enumerate(difference)),reverse=True,key=lambda x:x[1])[1:11] 
      for i in song_list:
            print(df_new.iloc[i[0]]['song'])


In [18]:
import pickle
pickle.dump(similarity, open('srs_model.pkl', 'wb'))

In [19]:
import pickle

pickle.dump(df_new.to_dict(), open('df.pkl','wb'))

#complete
